# -------------------------------------
# Minecraft Odyssey Config File
#
# -------------------------------------
#
#
names:
  server-name: "Vailcraft"

# enables or disables daily world events
daily-world-phenomenon:
  enabled: true
  slime-day-enabled: true
  blood-moon-enabled: true
  breezy-day-enabled: true

# dictates whether the end game is disabled
end-game:
  enabled: true

player-minimum-for-luck: 3

mega-events: true

server-join: true

# effect give @e[type=minecraft:ender_dragon] minecraft:resistance 9999 1
# effect give @e[type=minecraft:ender_dragon] minecraft:health_boost 9999 250
# effect give @e[type=minecraft:ender_dragon] minecraft:instant_health 9999 1