# -------------------------------------
# Minecraft Odyssey Config File
#
# -------------------------------------
#
#
names:
  server-name: "Vailcraft"

# enables or disables daily world events
daily-world-phenomenon:
  enabled: true
  slime-day-enabled: true
  blood-moon-enabled: true
  breezy-day-enabled: true

player-minimum-for-luck: 1

mega-events: true

server-join: true