# -------------------------------------
# Minecraft Odyssey Config File
#
# -------------------------------------
#
#
names:
  server-name: "Vailcraft"

# enables or disables daily world events
daily-world-events: true

mega-events: true

server-join: true