# -------------------------------------
# Minecraft Odyssey Config File
#
# -------------------------------------
#
#
names:
  server-name: "Vailcraft"

# enables or disables daily world events
daily-world-phenomenon: true

mega-events: true

server-join: true

player-minimum-for-luck: 3