# -------------------------------------
# Minecraft Odyssey Config File
#
# -------------------------------------
#
#
names:
  server-name: "Vailcraft"

# enables or disables daily world events
daily-world-phenomenon:
  enabled: true
  slime-day-enabled: true
  blood-moon-enabled: true
  breezy-day-enabled: true

# dictates whether the end game is disabled
end-game:
  enabled: false

player-minimum-for-luck: 3

mega-events: true

server-join: true